name: OpenOrClosed - Release

on:
  push:
    branches: [ master ]

env:
  SOLUTION: OpenOrClosed.sln
  PACKAGE_NAME: OpenOrClosed
  PLUGIN_PROJECT: OpenOrClosed\OpenOrClosed.csproj
  CORE_PROJECT: OpenOrClosed.Core\OpenOrClosed.Core.csproj
  OUTPUT_PATH: ${{ github.workspace }}\.output

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: echo "${{ secrets.NUGET_API_KEY }}".Length
      env:
        apiKey: ${{ secrets.NUGET_API_KEY }}
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: msbuild ${{ env.SOLUTION }} -t:restore

    - name: Copy lucene analyser
      run: |
        $src = "C:\Users\runneradmin\.nuget\packages\lucene.net\4.8.0-beta00014\analyzers\dotnet\cs"
        $dest = "C:\Users\runneradmin\.nuget\packages\lucene.net\3.0.3\analyzers\dotnet\cs"
        if (!(Test-Path -Path $dest)) {
            New-Item -ItemType directory -Path $dest
        }
        Copy-Item -Path $src\*.dll -Destination $dest

    - name: Create ${{ env.PACKAGE_NAME }} Nuget Packages
      run: msbuild ${{ env.SOLUTION }} -p:Configuration=Release -p:GeneratePackageOnBuild=true -p:PackageOutputPath=${{ env.OUTPUT_PATH }}
      
    - name: Publish ${{ env.PACKAGE_NAME }} to NuGet
      run: dotnet nuget push "${{ env.OUTPUT_PATH }}\*.nupkg" --skip-duplicate -n -k "$env:apiKey" -s https://api.nuget.org/v3/index.json
      env:
        apiKey: ${{ secrets.NUGET_API_KEY }}

    - name: Get Release Version
      id: package_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: PLUGIN_PROJECT

    - name: Create Release Tag
      run: |
        git tag -m "CI: create new tag" v${{ steps.test.package_version.version }}
        git push origin v${{ steps.test.package_version.version }}
